### ISSUE TITLE
error compile when run in console mode

### ISSUE THREAD

**Issue by hyhmm** [unity-plugins/google-services-unity#31]
error msg:Assets/Plugins/PlayGameAPI/FirebaseAnalytic.cs(15,27): error CS1061: Type `google.service.game.FirebaseAnalytic' does not contain a definition for `preInit' and no extension method `preInit' of type `
In FirebaseService.cs #if UNITY_ANDROID #elif UNITY_EDITOR #endif ,  can i change to  #if UNITY_ANDROID #else  #endif
I am poor in english

**Comment by unity-plugins** [comment]
Yes,You can edit any code

**Comment by hyhmm** [comment]
ok
