### ISSUE TITLE
Need info about permissions

### ISSUE THREAD

**Issue by j1and1** [unity-plugins/google-services-unity#32]
First of all I would like to say that this wrapper for google services is the best one on the interwebs! Keep up the good job guys!

Now for the question..... What permissions corespond to what service? I know that AdMob needs Internet permission also as Google Games and Firebase..... But why does it need to Read phone state and Location? and will it work without these permissions? Or will it hardcrash if there is no such permissions?

Is there a possibility to disable the services that needs those permissions and publish my game without them?

**Comment by unity-plugins** [comment]
You can try to remove that permissions and have a try. This plugin not need extra permissions except those of admob and game play service.

**Comment by j1and1** [comment]
Ok so tested out the permission thing.... basicly if you don't like the list of permissions in manifest you can remove all of them and just leave permissions regarding internet and its state....

**Comment by Kshopper93** [comment]
Had the same problem with other plugins. Add to all AndroidManifests  <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="23" /> with the same min and max sdk version. That fixed my problems with the permissions.
