### ISSUE TITLE
Package issue in Unity 5.6.6

### ISSUE THREAD

**Issue by waqasbhattii** [unity-plugins/google-services-unity#46]
Hello,

I am facing the following issue when i am importing this package into my Unity 5.6.6 project.

Please tell how to solve it.

<img width="1181" alt="screen shot 2018-09-12 at 5 40 44 pm" src="https://user-images.githubusercontent.com/43206618/45425589-418d9880-b6b3-11e8-9d30-5d0ab7a80e76.png">

**Comment by unity-plugins** [comment]
download the last version from https://github.com/unity-plugins/google-play-game-service-for-unity3d
