### ISSUE TITLE
onConnectFailed: {"errorCode":8,"isSuccess":false,"hasResolution":false}

### ISSUE THREAD

**Issue by ssoher** [unity-plugins/google-services-unity#6]
I now get this log in logcat. Was able to login correctly once, not anymore.

onConnectFailed: {"errorCode":8,"isSuccess":false,"hasResolution":false}

What does hasResolution mean? Where do I find all the error codes and their meanings?

**Comment by ssoher** [comment]
Turns out you can't login in Awake?

**Comment by Meyden** [comment]
I've got the same issue with "errorCode":7 ...
Did you find a solution ?

**Comment by ssoher** [comment]
Use the official Google plugins, they work perfectly https://developers.google.com/unity/

**Comment by mostdeep123** [comment]
but how do you integrate the AdMob API using that plugin ? did you know ?

**Comment by ssoher** [comment]
@mostdeep123 there are examples in the download and the documentation here is quite good https://firebase.google.com/docs/admob/unity/start

**Comment by AStox** [comment]
I believe these error codes refer to the ones referenced here in the Google Play Games API: https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult.html

From the link:
error code 8 is "INTERNAL_ERROR: An internal error occurred. Retrying should resolve the problem.";
error code 7 is "NETWORK_ERROR: A network error occurred. Retrying should resolve the problem."

I'm getting error code 8 as well, and retrying is not working...
